[tox]
envlist = python3.8 , python3.9

[gh-actions]
python = 
   3.8: python3.8
   3.9: python3.9


[testenv]
deps = -rrequirements_dev.txt
commands = 
   # stop the build if there are python syntax error or undefinied names 
   flake8 src --count --select=E9, F63, F7 , F82 --shpw-source --statistics
   #exit-zero treats all errorsas warnings. The GitHub editors is 127 char 
   flake8 scr --count --exit-zero --max-cpmplexity=10 --max-line-length=127
   #type linting 
   mypy src/
   #pytest unit
   pytest -v tests/unit 
   #pytest integration 
   pytest -v test/integration